username: "sxemshiki" # Имя пользователя Instagram, от имени которого будет выполняться вход
password: "1998artemQ" # Пароль от аккаунта Instagram

videos_to_download: 30 # Количество последних рилсов к скачиванию

download_folder: "downloads" # Путь к папке для сохранения скачанных видео
session_name: "session.json" # Название файла сессии

check_interval: 60 # Интервал проверки новых видео (в секундах)

# proxy: socks5://B8SHnMHa:N1TAkpN2@109.205.184.61:64491