username: "" # Имя пользователя Instagram, от имени которого будет выполняться вход
password: "" # Пароль от аккаунта Instagram
session_name: "session.json" # Название файла сессии

# proxy: socks5://B8SHnMHa:N1TAkpN2@109.205.184.61:64491

videos_to_download: 30 # Количество последних рилсов к скачиванию
download_folder: "downloads/videos" # Путь к папке для сохранения скачанных видео
output_folder": "downloads/unique_videos" # Путь к папке для сохранения уникализированных видео
image_name: "image.png" # Картинка для уникализации
uniqueize: "true" # true\false

# Настройки для папки 1
folder_1:
  folder_name: "test1"  # Название папки 1
  times: ["18:00", "21:00", "12:00"]  # Время публикации видео из папки 1
  descriptions:  # Описания для видео из папки 1
    - "Описание 1 для видео из папки 1"
    - "Описание 2 для видео из папки 1"
    - "Описание 3 для видео из папки 1"

# Настройки для папки 2
folder_2:
  foldere_name: "test2"  # Название папки 2
  times: ["15:00", "16:00", "17:00"]  # Время публикации видео из папки 2
  descriptions:  # Описания для видео из папки 2
    - "Описание 1 для видео из папки 2"
    - "Описание 2 для видео из папки 2"
    - "Описание 3 для видео из папки 2"