username: "" # Имя пользователя Instagram, от имени которого будет выполняться вход
password: "" # Пароль от аккаунта Instagram
session_name: "session.json" # Название файла сессии

videos_to_download: 30 # Количество последних рилсов к скачиванию
download_folder: "downloads/videos" # Путь к папке для сохранения скачанных видео
output_folder": "downloads/unique_videos" # Путь к папке для сохранения уникализированных видео
image_name: "image.png" # Картинка для уникализации
uniqueize: "true" # true\false

# proxy: socks5://B8SHnMHa:N1TAkpN2@109.205.184.61:64491